### ISSUE TITLE
Extract embeddings/predict for new data after trained the model?

### ISSUE THREAD

**Issue by DavidHarar** [xinyandai/string-embed#10]
Hi, 

Thanks for the great work and the ingenious paper! 

I trained a model based on the line that is given on the project's page, specifically:  

``python main.py --dataset word --nt 1000 --nq 1000 --epochs 20 --save-split --recall --save-model
``
Now I have the trained model (I know it is not the version that is presented in the paper), and a list of two words, how can I use the model in order to predict their edit distance? 
I got lost going through the preprocessing stage. 

Thanks again, and sorry for the noob question :)

**Comment by julian-di** [comment]
Hi do you have any updates on this, how did you end up using it?
