### ISSUE TITLE
您好，请问下我的这个理解对么？

### ISSUE THREAD

**Issue by guotong1988** [xinyandai/string-embed#5]
用编辑距离得到的数据作为训练数据训练一个模型，然后recall-item会提升？
正负例是如何构造的？比BM25效果怎样？
@xinyandai 多谢多谢多谢！

**Comment by anonymouspaperowner** [comment]
- 是先有训练数据，然后再计算出编辑距离来训练。训练出来的模型可以给sequence做embedding，embedding上的距离可以近似edit distance。
- 正负例的构造在https://arxiv.org/abs/2001.11692文章的3.1有说，大概就是对一个字符串（s），再在数据集中找两个字符串，近一个与s组成正例，远点的那个与s组成负例。
- 没有比过BM25, 如果BM25可以用于edit distance的话。

**Comment by xinyandai** [comment]
- 是先有训练数据，然后再计算出编辑距离来训练。训练出来的模型可以给sequence做embedding，embedding上的距离可以近似edit distance。
-正负例的构造在[文章](https://arxiv.org/abs/2001.11692) 的3.1介绍，大概就是对一个字符串（s），再在数据集中找两个字符串，近一个与s组成正例，远点的那个与s组成负例。
- 没有比过BM25, 如果BM25可以用于edit distance的话。

**Comment by guotong1988** [comment]
”先有训练数据，然后再计算出编辑距离来训练“

这块可以举个例子吗？

**Comment by xinyandai** [comment]
Given a training set, the edit distances between all pairs of items are computed. 
To obtain a triplet, a random string is sampled from the training set as s_acr. Then two of its top-k neighbours (k =100 by default) are sampled, and the one having smaller edit distance with s_acr is used as s_pos while the other one is used as s_neg.
