### ISSUE TITLE
Duplicate self.Ls. Merge error?

### ISSUE THREAD

**Issue by fjsj** [xinyandai/string-embed#7]
Hi, thanks for sharing the code from the paper! I think I found a bug, looks like a git merge issue:

https://github.com/xinyandai/string-embed/blob/8a8a2ead4b77dc7ef265fcebc8f1b1549935ce58/networks.py#L412-L425

Should be only one of the `self.Ls`, right?
And it seems the current master version is not using the `mse_loss`, since it's all zero.

**Comment by xinyandai** [comment]
Oh, that's an accident commit when tuning the parameters.  Yes, the first one should be used otherwise mse_loss is ignored.

**Comment by xinyandai** [comment]
Thanks for pointing it out. Now it is fixed.
