### ISSUE TITLE
View is across batch instances?

### ISSUE THREAD

**Issue by fjsj** [xinyandai/string-embed#8]
https://github.com/xinyandai/string-embed/blob/61e03475ad8d5b28db6a67e85ffd2473e60a421e/networks.py#L71-L72

It seems to be this code is making `x` to mix values from different batch instances. Instead, I think it should be `x = x.view(x.size(0), self.mtc_input, -1)`

**Comment by aalennku** [comment]
![image](https://user-images.githubusercontent.com/6031710/115986527-2ad9ad00-a5e3-11eb-8489-e311df7e3293.png)
It seems that the code runs correctly
![image](https://user-images.githubusercontent.com/6031710/115986565-58bef180-a5e3-11eb-9d46-a64d94410ec2.png)
I guess the author had tried several versions of the data structure. 
and the final version lacks cleanup, which works correctly anyway.

**Comment by fjsj** [comment]
Thanks, I understand the code works, I've used it too.
But I guess it's not desirable to mix batch instances.

**Comment by xinyandai** [comment]
So sorry for the delay. @fjsj 
Thank you for your explanation and verification. @aalennku 



The input strings are **shape of (N,  C, M)**, 
* if mtc_input is disabled:  
  - 1D-Conv-s with **one channel** are applied on each row of the input strings  **(shape of 1xM)**.
  - we reshape input into shape of (N * C, 1, M)
* if mtc_input is enabled:  
  - 1D-Conv-s with **$C$ channels** are applied on each input string (**shape of CxM**).
  - we reshpae input into shape of (N, C, M)
 
The following codes are equivalent:
```python 
x = x.view(-1, self.mtc_input, self.M) 
```

```python
 N = s.size(0) # number of batchse
 C = ...            # number of distince characters
 M = ...            # maximum string length
 if mtc_input: # .i.e., self.mtc_input == 1
     x = x.view(N * C, 1, self.M) 
 else:             # , i.e., self.mtc_input == 1
     x = x.view(N, C, self.M)
````

In the paper, we use the version that **mtc_input is disabled**.
